# Generated by Django 5.0.7 on 2024-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtua',
            field=models.URLField(blank=True, null=True),
        ),
    ]
