# Generated by Django 5.0.4 on 2024-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_footage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='mls_number',
            field=models.CharField(default='MLS0000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_name',
            field=models.CharField(default='Unknown Street', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='subdivision',
            field=models.CharField(default='Unknown Subdivision', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
