# Generated by Django 5.0.7 on 2024-10-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_property_virtua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='virtua',
        ),
    ]
