# Generated by Django 5.0.4 on 2024-08-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_property_address_remove_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(),
        ),
    ]
