# Generated by Django 5.0.7 on 2024-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_property_latitude_property_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(upload_to="property_images/"),
        ),
    ]
