# Generated by Django 5.0.7 on 2024-10-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_mls_number_property_mls_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='mls_numbers',
            new_name='mls_number',
        ),
    ]
