# Generated by Django 5.0.7 on 2024-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="baths",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="subdivision",
            field=models.CharField(max_length=100),
        ),
    ]
