# Generated by Django 5.0.7 on 2024-11-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_mls_numbers_property_mls_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='car_port_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
