# Generated by Django 5.0.7 on 2024-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_property_baths_remove_property_subdivision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
