# Generated by Django 5.0.7 on 2024-11-02 03:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_property_car_port_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
