# Generated by Django 5.0.7 on 2024-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_property_private_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertysubtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
