# Generated by Django 5.0.7 on 2024-08-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_property_propertysubtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertysubtype',
        ),
        migrations.AddField(
            model_name='property',
            name='property_subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
