# Generated by Django 5.0.7 on 2024-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_property_propertysubtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavicaProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BedroomsTotal', models.IntegerField(blank=True, null=True)),
                ('GarageYN', models.BooleanField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('PublicRemarks', models.CharField(blank=True, max_length=10000, null=True)),
                ('CountyOrParish', models.CharField(blank=True, max_length=10000, null=True)),
                ('BathroomsTotalDecimal', models.FloatField(blank=True, null=True)),
                ('ListPrice', models.IntegerField(blank=True, null=True)),
                ('UnparsedAddress', models.CharField(blank=True, max_length=10000, null=True)),
                ('YearBuilt', models.IntegerField(blank=True, null=True)),
                ('SourceSystemKey', models.CharField(max_length=10000, unique=True)),
                ('HighSchoolDistrict', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
