# Generated by Django 5.0.7 on 2024-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_navicaproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='mls_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
