# Generated by Django 5.0.7 on 2024-10-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_propertyimage_mls_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='listing',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='mls_number',
        ),
    ]
