# Generated by Django 5.0.7 on 2024-10-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_listing_propertyimage_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='appliances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_materials',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cooling',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='highschool_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='interior_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='levels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='middle_junior_school_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mls_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='roof',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sewer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='subdivision_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths_full',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths_half',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='baths_three_quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
