# Generated by Django 5.0.7 on 2024-10-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_property_appliances_property_building_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths_total_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carport_spaces',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='days_on_market',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electric',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='exterior_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fireplace_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fireplace_yes_no',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='foundation_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_yes_no',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='heating_yes_no',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='patio_porch_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pool_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pool_private_yes_no',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='proad_surface_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
