# Generated by Django 5.0.7 on 2024-10-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_property_baths_total_integer_property_carport_spaces_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='carport_spaces',
            new_name='car_port_spaces',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='lot_size',
            new_name='lot_size_acres',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='proad_surface_type',
            new_name='road_surface_type',
        ),
    ]
