# Generated by Django 5.0.7 on 2024-10-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_property_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='mls_area',
        ),
    ]
