# Generated by Django 5.0.7 on 2024-10-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_property_address_is_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_from', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('baths_full', models.IntegerField(blank=True, null=True)),
                ('baths_half', models.IntegerField(blank=True, null=True)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='app.property')),
            ],
        ),
    ]
