# Generated by Django 5.0.7 on 2024-10-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_property_address_is_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='other_structures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_change_timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lot_size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
