# Generated by Django 5.0.7 on 2024-10-19 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='app.property'),
        ),
    ]
