# Generated by Django 5.0.7 on 2024-10-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_rental_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='baths_full',
            new_name='baths',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='pets_allowed',
            new_name='fenced_yard',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='description',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='baths_half',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='property',
        ),
        migrations.AddField(
            model_name='rental',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='street_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
