# Generated by Django 5.0.7 on 2024-10-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_property_other_structures_and_more'),
        ('app', '0026_rentalimage'),
    ]

    operations = [
    ]
